apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mon-ingress-toto
  labels:
    name: mon-ingress-toto
spec:
  rules:
  - host: mercredi-greve.dev.insee.io
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: mon-service-toto
            port: 
              number: 8080 
