apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14.4
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: db0
            - name: POSTGRES_USER
              value: postgres-secret
            - name: POSTGRES_PASSWORD
              value: postgres-passwd
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: "user-pgdata"
      volumes:
        - hostPath:
            path: "/home/docker/pgdata"
          name: user-pgdata